/** @remark this is auto-generated file, do not edit
 * generated by bash script
 * */
var APIFieldEnum = function () {
    this._ = "APIField";
    this.action = "action";
    this.result_code = "result_code";
    this.data = "data";
    this.reason = "reason";
    this.emailOrPhoneNum = "emailOrPhoneNum";
    this.password = "password";
    this.session_id = "session_id";
    this.element_array = "element_array";
    this.profile = "profile";
    this.table_name_array = "table_name_array";
    this.table_name = "table_name";
    this.latest_id = "latest_id";
    this.id_array = "id_array";
    this.id = "id";
    this.field_array = "field_array";
    this.message = "message";
    this.followed = "followed";
    this.following = "following";
    this.joined = "joined";
    this.join_time = "join_time";
};
var APIField = new APIFieldEnum();
