/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
var organization_type_Enum = function () {
    this.business = "business" ;
    this.academic = "academic" ;
};
var organization_type = new organization_type_Enum();