#!/usr/bin/env bash
## argument : port [optional]

function start_server() {
  bash make
  php -S "0.0.0.0:$1" -t public  
}

if [ $# -eq 0 ] ; then
#  echo "Please specify the port number"
  echo "Using default port 8000"
  start_server 8000
else
  echo "Using port $1"
  start_server $1
fi


