#!/bin/bash
## generate java file from idl
#idlj -td out/ src/main.idl
idlj -fserver -td out/ src/main.idl
# idlj -td out/ src/main.idl
rm ../webapp-server/app/models/idl -rf
mv out/models/idl/ ../webapp-server/app/models
rm ../webapp-server/app/models/idl/social_connection/*POA.java
# rm ../webapp-server/app/models/idl/social_connection/*Helper.java
# rm ../webapp-server/app/models/idl/social_connection/*Holder.java
# rm ../webapp-server/app/models/idl/social_connection/_*Stub.java

## generate php file from java

bash ./script/ResultCodeEnum.sh > ../server/api/debug/ResultCodeEnum.php
#bash ./script/SexEnum.sh > ../server/api/database/enum/SexEnum.php
