#!/bin/bash
## generate java file from idl
#idlj -td out/ src/main.idl
idlj -fserver -td out/ src/main.idl
# idlj -td out/ src/main.idl
rm ../webapp-server/app/models/idl -rf
mv out/models/idl/ ../webapp-server/app/models
rm ../webapp-server/app/models/idl/social_connection/*POA.java
# rm ../webapp-server/app/models/idl/social_connection/*Helper.java
# rm ../webapp-server/app/models/idl/social_connection/*Holder.java
# rm ../webapp-server/app/models/idl/social_connection/_*Stub.java

## generate php file from java
bash ./script/make_enum_php.sh ResultCode > ../server/api/enum/ResultCodeEnum.php
bash ./script/make_enum_php.sh ResultField > ../server/api/enum/ResultFieldEnum.php

## generate javascript file from java
bash ./script/make_enum_js.sh ResultCode > ../public/js/enum/ResultCodeEnum.js
bash ./script/make_enum_js.sh ResultField > ../public/js/enum/ResultFieldEnum.js
