#!/bin/bash
## generate java file from idl
#idlj -td out/ src/main.idl
idlj -fserver -td out/ src/main.idl
# idlj -td out/ src/main.idl
rm ../webapp-server/app/models/idl -rf
mv out/models/idl/ ../webapp-server/app/models
rm ../webapp-server/app/models/idl/social_connection/*POA.java
# rm ../webapp-server/app/models/idl/social_connection/*Helper.java
# rm ../webapp-server/app/models/idl/social_connection/*Holder.java
# rm ../webapp-server/app/models/idl/social_connection/_*Stub.java

## generate php file from java
bash ./script/make_enum_number_php.sh ResultCode > ../server/api/enum/ResultCodeEnum.php
bash ./script/make_enum_string_php.sh APIField > ../server/api/enum/APIFieldEnum.php

## generate javascript file from java
bash ./script/make_enum_string_js.sh ResultCode > ../public/js/enum/ResultCodeEnum.ts
bash ./script/make_enum_string_js.sh APIField > ../public/js/enum/APIFieldEnum.ts

## generate javascript file from php API
bash ./script/make_api_list_js.sh > ../public/js/api_list.ts