/** @remark this is auto-generated file, do not edit
 * generated by bash script
 * */
var _api_Util = "Util";
var _api_API = "API";
var _api_CreateUser = "CreateUser";
var _api_IsEmailOrPhoneNumUnique = "IsEmailOrPhoneNumUnique";
var _api_Login = "Login";
var _api_GetUserListInfo = "GetUserListInfo";
var _api_EditProfile = "EditProfile";
var _api_GetProfileList = "GetProfileList";
var _api_Follow = "Follow";
var _api_CreateAnnouncement = "CreateAnnouncement";
var _api_GetNewAnnouncement = "GetNewAnnouncement";
var _api_GetAnnouncementList = "GetAnnouncementList";
var _api_CreateSession = "CreateSession";
var _api_CreateExhibition = "CreateExhibition";
var _api_GetTitleList = "GetTitleList";
var _api_GetOrganizationList = "GetOrganizationList";
var _api_GetCountryList = "GetCountryList";
var _api_GetCityList = "GetCityList";
var _api_EditOrganization = "EditOrganization";
var _api_GetLatestIdList = "GetLatestIdList";
var _api_CreateAttraction = "CreateAttraction";
var _api_GetTableRowList = "GetTableRowList";
var _api_AddTableRowList = "AddTableRowList";
var _api_GetMessageList = "GetMessageList";
var _api_GetEventList = "GetEventList";
var _api_GetAttractionList = "GetAttractionList";
var _api_GetSessionList = "GetSessionList";
var _api_GetExhibitionList = "GetExhibitionList";
var _api_CreateMessage = "CreateMessage";
var _api_GetFollowedList = "GetFollowedList";
var _api_GetFollowerList = "GetFollowerList";
var _api_GetProfile = "GetProfile";
