<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class account_type_Enum {
    const __admin = "admin" ;
    const __helper = "helper" ;
    const __attendee = "attendee" ;
}