<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class sex_Enum {
    const __F = "F" ;
    const __M = "M" ;
    const __other = "other" ;
    const __unknown = "unknown" ;
}