module Station{
  interface ObjectStation{
    typedef sequence<Object> ObjectSequence;
    struct ObjectStruct{
      string object_name;
      ObjectSequence object_refs;
      short num_object_refs;
    };
    void register(in ObjectStruct new_object);
    exception Object_Unknown{
      string err_msg;
    };
    ObjectSequence lookup(in string object_name,out short num_object_refs) raises (Object_Unknown);
    void de_register(in string object_name) raises(Object_Unknown);
  };
};