/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Account_stub {
    public static table_name:string = "Account" ;

    public static __account_id:string = "account_id";
    public static __password:string = "password";
    public static __account_type:string = "account_type";
    public static __email:string = "email";
    public static __phone_num:string = "phone_num";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Account {
        //TODO
        var myAccount = new Account();
        myAccount.account_id = rawObject.account_id;
        myAccount.password = rawObject.password;
        myAccount.account_type = rawObject.account_type;
        myAccount.email = rawObject.email;
        myAccount.phone_num = rawObject.phone_num;
        return myAccount;
    }

    public static get_all_instance($http):Account[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Account {
    public static table_name:string = "Account" ;

    public account_id:number;
    public password:string;
    public account_type:string;
    public email:string;
    public phone_num:string;
}