///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Account_stub extends stub.DataObject {

    /* key */
    protected static __account_id:string = "account_id";
    protected static __password:string = "password";
    protected static __account_type:string = "account_type";
    protected static __email:string = "email";
    protected static __phone_num:string = "phone_num";

    /* implement DataObject */
    tableName():string {
      return "Account";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("account_id");
      list.push("password");
      list.push("account_type");
      list.push("email");
      list.push("phone_num");
      return list;
    }
    
    parseObject(rawObject:any):Account_stub {
      return null;//TODO
    }
    
    toObject(instant:Account_stub):any {
      return null;//TODO
    }

    /* variable */
    private account_id:number;
    private password:string;
    private account_type:string;
    private email:string;
    private phone_num:string;

  }
}