/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Announcement_stub {
    public static table_name:string = "Announcement" ;

    public static __announcement_id:string = "announcement_id";
    public static __subject:string = "subject";
    public static __description:string = "description";
    public static __create_time:string = "create_time";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Announcement {
        //TODO
        var myAnnouncement = new Announcement();
        myAnnouncement.announcement_id = rawObject.announcement_id;
        myAnnouncement.subject = rawObject.subject;
        myAnnouncement.description = rawObject.description;
        myAnnouncement.create_time = rawObject.create_time;
        return myAnnouncement;
    }

    public static get_all_instance($http):Announcement[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Announcement {
    public static table_name:string = "Announcement" ;

    public announcement_id:number;
    public subject:string;
    public description:string;
    public create_time:string;
}