///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Announcement_stub extends stub.DataObject {

    /* key */
    protected static __announcement_id:string = "announcement_id";
    protected static __subject:string = "subject";
    protected static __description:string = "description";
    protected static __create_time:string = "create_time";

    /* implement DataObject */
    tableName():string {
      return "Announcement";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("announcement_id");
      list.push("subject");
      list.push("description");
      list.push("create_time");
      return list;
    }
    
    parseObject(rawObject:any):Announcement_stub {
      return null;//TODO
    }
    
    toObject(instant:Announcement_stub):any {
      return null;//TODO
    }

    /* variable */
    private announcement_id:number;
    private subject:string;
    private description:string;
    private create_time:string;

  }
}