///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class City_stub extends stub.DataObject {

    /* key */
    protected static __city_id:string = "city_id";
    protected static __country_id:string = "country_id";
    protected static __city_name:string = "city_name";

    /* implement DataObject */
    tableName():string {
      return "City";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("city_id");
      list.push("country_id");
      list.push("city_name");
      return list;
    }
    
    parseObject(rawObject:any):City_stub {
      return null;//TODO
    }
    
    toObject(instant:City_stub):any {
      return null;//TODO
    }

    /* variable */
    private city_id:number;
    private country_id:number;
    private city_name:string;

  }
}