///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class City_stub extends stub.DataObject {

    /* key */
    protected static __city_id():string {
      return "city_id";
    }

    protected static __country_id():string {
      return "country_id";
    }

    protected static __city_name():string {
      return "city_name";
    }

    /* implement DataObject */
    tableName():string {
      return "City";
    }
    
    uniqueKeyList():string[] {
      var list:string[] = [];
      list.push("city_id");
      list.push("city_name");
      return list;
    }
    
    parseObject(rawObject:any):City_stub {
      return null;//TODO
    }
    
    toObject(instant:City_stub):any {
      return null;//TODO
    }

    /* variable */
    private city_id:number;
    private country_id:number;
    private city_name:string;

    /* getter and setter */
    public get_city_id():number {
      return this.city_id;
    }

    public set_city_id(newValue:number) {
      if (this.isEditSupport()) {
        this.city_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_country_id():number {
      return this.country_id;
    }

    public set_country_id(newValue:number) {
      if (this.isEditSupport()) {
        this.country_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_city_name():string {
      return this.city_name;
    }

    public set_city_name(newValue:string) {
      if (this.isEditSupport()) {
        this.city_name = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

  }
}