/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class City_stub {
    public static table_name:string = "City" ;

    public static __city_id:string = "city_id";
    public static __country_id:string = "country_id";
    public static __city_name:string = "city_name";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):City {
        //TODO
        var myCity = new City();
        myCity.city_id = rawObject.city_id;
        myCity.country_id = rawObject.country_id;
        myCity.city_name = rawObject.city_name;
        return myCity;
    }

    public static get_all_instance($http):City[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class City {
    public static table_name:string = "City" ;

    public city_id:number;
    public country_id:number;
    public city_name:string;
}