///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Country_stub extends stub.DataObject {

    /* key */
    protected static __country_id:string = "country_id";
    protected static __country_name:string = "country_name";

    /* implement DataObject */
    tableName():string {
      return "Country";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("country_id");
      list.push("country_name");
      return list;
    }
    
    parseObject(rawObject:any):Country_stub {
      return null;//TODO
    }
    
    toObject(instant:Country_stub):any {
      return null;//TODO
    }

    /* variable */
    private country_id:number;
    private country_name:string;

  }
}