/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Country_stub {
    public static table_name:string = "Country" ;

    public static __country_id:string = "country_id";
    public static __country_name:string = "country_name";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Country {
        //TODO
        var myCountry = new Country();
        myCountry.country_id = rawObject.country_id;
        myCountry.country_name = rawObject.country_name;
        return myCountry;
    }

    public static get_all_instance($http):Country[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Country {
    public static table_name:string = "Country" ;

    public country_id:number;
    public country_name:string;
}