/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class DiscussBoard_stub {
    public static table_name:string = "DiscussBoard" ;

    public static __discussboard_id:string = "discussboard_id";
    public static __subject:string = "subject";
    public static __description:string = "description";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):DiscussBoard {
        //TODO
        var myDiscussBoard = new DiscussBoard();
        myDiscussBoard.discussboard_id = rawObject.discussboard_id;
        myDiscussBoard.subject = rawObject.subject;
        myDiscussBoard.description = rawObject.description;
        return myDiscussBoard;
    }

    public static get_all_instance($http):DiscussBoard[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class DiscussBoard {
    public static table_name:string = "DiscussBoard" ;

    public discussboard_id:number;
    public subject:string;
    public description:string;
}