///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class DiscussBoard_stub extends stub.DataObject {

    /* key */
    protected static __discussboard_id:string = "discussboard_id";
    protected static __subject:string = "subject";
    protected static __description:string = "description";

    /* implement DataObject */
    tableName():string {
      return "DiscussBoard";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("discussboard_id");
      list.push("subject");
      list.push("description");
      return list;
    }
    
    parseObject(rawObject:any):DiscussBoard_stub {
      return null;//TODO
    }
    
    toObject(instant:DiscussBoard_stub):any {
      return null;//TODO
    }

    /* variable */
    private discussboard_id:number;
    private subject:string;
    private description:string;

  }
}