///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Event_Attendee_stub extends stub.DataObject {

    /* key */
    protected static __event_id:string = "event_id";
    protected static __account_id:string = "account_id";

    /* implement DataObject */
    tableName():string {
      return "Event_Attendee";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("event_id");
      list.push("account_id");
      return list;
    }
    
    parseObject(rawObject:any):Event_Attendee_stub {
      return null;//TODO
    }
    
    toObject(instant:Event_Attendee_stub):any {
      return null;//TODO
    }

    /* variable */
    private event_id:number;
    private account_id:number;

  }
}