/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Event_stub {
    public static table_name:string = "Event" ;

    public static __event_id:string = "event_id";
    public static __create_time:string = "create_time";
    public static __edit_time:string = "edit_time";
    public static __event_type:string = "event_type";
    public static __venue_id:string = "venue_id";
    public static __event_time:string = "event_time";
    public static __creator_account_id:string = "creator_account_id";
    public static __editor_account_id:string = "editor_account_id";
    public static __subject:string = "subject";
    public static __description:string = "description";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Event {
        //TODO
        var myEvent = new Event();
        myEvent.event_id = rawObject.event_id;
        myEvent.create_time = rawObject.create_time;
        myEvent.edit_time = rawObject.edit_time;
        myEvent.event_type = rawObject.event_type;
        myEvent.venue_id = rawObject.venue_id;
        myEvent.event_time = rawObject.event_time;
        myEvent.creator_account_id = rawObject.creator_account_id;
        myEvent.editor_account_id = rawObject.editor_account_id;
        myEvent.subject = rawObject.subject;
        myEvent.description = rawObject.description;
        return myEvent;
    }

    public static get_all_instance($http):Event[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Event {
    public static table_name:string = "Event" ;

    public event_id:number;
    public create_time:string;
    public edit_time:string;
    public event_type:string;
    public venue_id:number;
    public event_time:string;
    public creator_account_id:number;
    public editor_account_id:number;
    public subject:string;
    public description:string;
}