///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Event_stub extends stub.DataObject {

    /* key */
    protected static __event_id:string = "event_id";
    protected static __create_time:string = "create_time";
    protected static __edit_time:string = "edit_time";
    protected static __event_type:string = "event_type";
    protected static __venue_id:string = "venue_id";
    protected static __event_time:string = "event_time";
    protected static __creator_account_id:string = "creator_account_id";
    protected static __editor_account_id:string = "editor_account_id";
    protected static __subject:string = "subject";
    protected static __description:string = "description";

    /* implement DataObject */
    tableName():string {
      return "Event";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("event_id");
      list.push("create_time");
      list.push("edit_time");
      list.push("event_type");
      list.push("venue_id");
      list.push("event_time");
      list.push("creator_account_id");
      list.push("editor_account_id");
      list.push("subject");
      list.push("description");
      return list;
    }
    
    parseObject(rawObject:any):Event_stub {
      return null;//TODO
    }
    
    toObject(instant:Event_stub):any {
      return null;//TODO
    }

    /* variable */
    private event_id:number;
    private create_time:string;
    private edit_time:string;
    private event_type:string;
    private venue_id:number;
    private event_time:string;
    private creator_account_id:number;
    private editor_account_id:number;
    private subject:string;
    private description:string;

  }
}