/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Event_Attendee_stub {
    public static table_name:string = "Event_Attendee" ;

    public static __event_id:string = "event_id";
    public static __account_id:string = "account_id";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Event_Attendee {
        //TODO
        var myEvent_Attendee = new Event_Attendee();
        myEvent_Attendee.event_id = rawObject.event_id;
        myEvent_Attendee.account_id = rawObject.account_id;
        return myEvent_Attendee;
    }

    public static get_all_instance($http):Event_Attendee[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Event_Attendee {
    public static table_name:string = "Event_Attendee" ;

    public event_id:number;
    public account_id:number;
}