///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Event_Organization_stub extends stub.DataObject {

    /* key */
    protected static __event_id():string {
      return "event_id";
    }

    protected static __organization_id():string {
      return "organization_id";
    }

    /* implement DataObject */
    tableName():string {
      return "Event_Organization";
    }
    
    uniqueKeyList():string[] {
      var list:string[] = [];
      list.push("event_id");
      list.push("organization_id");
      return list;
    }
    
    parseObject(rawObject:any):Event_Organization_stub {
      var instance = new Event_Organization_stub();
      instance.event_id = rawObject.event_id;
      instance.organization_id = rawObject.organization_id;
      return instance;
    }
    
    toObject(instance:Event_Organization_stub=this):any {
      var rawObject = {};
      rawObject[Event_Organization_stub.__event_id()] = instance.event_id;
      rawObject[Event_Organization_stub.__organization_id()] = instance.organization_id;
      return rawObject;
    }

    /* variable */
    private event_id:number;
    private organization_id:number;

    /* getter and setter */
    public get_event_id():number {
      return this.event_id;
    }

    public set_event_id(newValue:number) {
      if (this.isEditSupport()) {
        this.event_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_organization_id():number {
      return this.organization_id;
    }

    public set_organization_id(newValue:number) {
      if (this.isEditSupport()) {
        this.organization_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

  }
}