/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Exhibition_stub {
    public static table_name:string = "Exhibition" ;

    public static __event_id:string = "event_id";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Exhibition {
        //TODO
        var myExhibition = new Exhibition();
        myExhibition.event_id = rawObject.event_id;
        return myExhibition;
    }

    public static get_all_instance($http):Exhibition[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Exhibition {
    public static table_name:string = "Exhibition" ;

    public event_id:number;
}