///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Floor_stub extends stub.DataObject {

    /* key */
    protected static __floor_id:string = "floor_id";
    protected static __name:string = "name";

    /* implement DataObject */
    tableName():string {
      return "Floor";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("floor_id");
      list.push("name");
      return list;
    }
    
    parseObject(rawObject:any):Floor_stub {
      return null;//TODO
    }
    
    toObject(instant:Floor_stub):any {
      return null;//TODO
    }

    /* variable */
    private floor_id:number;
    private name:string;

  }
}