/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Floor_stub {
    public static table_name:string = "Floor" ;

    public static __floor_id:string = "floor_id";
    public static __name:string = "name";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Floor {
        //TODO
        var myFloor = new Floor();
        myFloor.floor_id = rawObject.floor_id;
        myFloor.name = rawObject.name;
        return myFloor;
    }

    public static get_all_instance($http):Floor[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Floor {
    public static table_name:string = "Floor" ;

    public floor_id:number;
    public name:string;
}