/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Friendship_Tag_stub {
    public static table_name:string = "Friendship_Tag" ;

    public static __friendship_id:string = "friendship_id";
    public static __tag_id:string = "tag_id";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Friendship_Tag {
        //TODO
        var myFriendship_Tag = new Friendship_Tag();
        myFriendship_Tag.friendship_id = rawObject.friendship_id;
        myFriendship_Tag.tag_id = rawObject.tag_id;
        return myFriendship_Tag;
    }

    public static get_all_instance($http):Friendship_Tag[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Friendship_Tag {
    public static table_name:string = "Friendship_Tag" ;

    public friendship_id:number;
    public tag_id:number;
}