///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Friendship_stub extends stub.DataObject {

    /* key */
    protected static __friendship_id:string = "friendship_id";
    protected static __host_id:string = "host_id";
    protected static __guest_id:string = "guest_id";
    protected static __remark:string = "remark";

    /* implement DataObject */
    tableName():string {
      return "Friendship";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("friendship_id");
      list.push("host_id");
      list.push("guest_id");
      list.push("remark");
      return list;
    }
    
    parseObject(rawObject:any):Friendship_stub {
      return null;//TODO
    }
    
    toObject(instant:Friendship_stub):any {
      return null;//TODO
    }

    /* variable */
    private friendship_id:number;
    private host_id:number;
    private guest_id:number;
    private remark:string;

  }
}