///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Image_stub extends stub.DataObject {

    /* key */
    protected static __image_id():string {
      return "image_id";
    }

    protected static __url():string {
      return "url";
    }

    /* implement DataObject */
    tableName():string {
      return "Image";
    }
    
    uniqueKeyList():string[] {
      var list:string[] = [];
      list.push("image_id");
      return list;
    }
    
    parseObject(rawObject:any):Image_stub {
      var instance = new Image_stub();
      if(rawObject.hasOwnProperty('image_id'))
        instance.image_id = rawObject.image_id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('url'))
        instance.url = rawObject.url;
      else
        throw new stub.DataObjectParseError(this);
      return instance;
    }
    
    toObject(instance:Image_stub=this):any {
      var rawObject = {};
      rawObject[Image_stub.__image_id()] = instance.image_id;
      rawObject[Image_stub.__url()] = instance.url;
      return rawObject;
    }

    /* variable */
    private image_id:number;
    private url:string;

    /* getter and setter */
    public get_image_id():number {
      return this.image_id;
    }

    public set_image_id(newValue:number) {
      if (this.isEditSupport()) {
        this.image_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_url():string {
      return this.url;
    }

    public set_url(newValue:string) {
      if (this.isEditSupport()) {
        this.url = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

  }
  stub.add_stub_instance(new Image_stub());
}