///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Image_stub extends stub.DataObject {

    /* key */
    protected static __image_id:string = "image_id";
    protected static __url:string = "url";

    /* implement DataObject */
    tableName():string {
      return "Image";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("image_id");
      list.push("url");
      return list;
    }
    
    parseObject(rawObject:any):Image_stub {
      return null;//TODO
    }
    
    toObject(instant:Image_stub):any {
      return null;//TODO
    }

    /* variable */
    private image_id:number;
    private url:string;

  }
}