/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Image_stub {
    public static table_name:string = "Image" ;

    public static __image_id:string = "image_id";
    public static __url:string = "url";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Image {
        //TODO
        var myImage = new Image();
        myImage.image_id = rawObject.image_id;
        myImage.url = rawObject.url;
        return myImage;
    }

    public static get_all_instance($http):Image[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Image {
    public static table_name:string = "Image" ;

    public image_id:number;
    public url:string;
}