///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class JsonArray_stub extends stub.DataObject {

    /* key */
    protected static __JsonArray_id():string {
      return "JsonArray_id";
    }

    protected static __JsonArray_content():string {
      return "JsonArray_content";
    }

    /* implement DataObject */
    tableName():string {
      return "JsonArray";
    }
    
    uniqueKeyList():string[] {
      var list:string[] = [];
      list.push("JsonArray_id");
      return list;
    }
    
    parseObject(rawObject:any):JsonArray_stub {
      return null;//TODO
    }
    
    toObject(instant:JsonArray_stub):any {
      return null;//TODO
    }

    /* variable */
    private JsonArray_id:number;
    private JsonArray_content:string;

    /* getter and setter */
    public get_JsonArray_id():number {
      return this.JsonArray_id;
    }

    public set_JsonArray_id(newValue:number) {
      if (this.isEditSupport()) {
        this.JsonArray_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_JsonArray_content():string {
      return this.JsonArray_content;
    }

    public set_JsonArray_content(newValue:string) {
      if (this.isEditSupport()) {
        this.JsonArray_content = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

  }
}