///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class JsonArray_stub extends stub.DataObject {

    /* key */
    protected static __JsonArray_id:string = "JsonArray_id";
    protected static __JsonArray_content:string = "JsonArray_content";

    /* implement DataObject */
    tableName():string {
      return "JsonArray";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("JsonArray_id");
      list.push("JsonArray_content");
      return list;
    }
    
    parseObject(rawObject:any):JsonArray_stub {
      return null;//TODO
    }
    
    toObject(instant:JsonArray_stub):any {
      return null;//TODO
    }

    /* variable */
    private JsonArray_id:number;
    private JsonArray_content:string;

  }
}