/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class JsonArray_stub {
    public static table_name:string = "JsonArray" ;

    public static __JsonArray_id:string = "JsonArray_id";
    public static __JsonArray_content:string = "JsonArray_content";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):JsonArray {
        //TODO
        var myJsonArray = new JsonArray();
        myJsonArray.JsonArray_id = rawObject.JsonArray_id;
        myJsonArray.JsonArray_content = rawObject.JsonArray_content;
        return myJsonArray;
    }

    public static get_all_instance($http):JsonArray[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class JsonArray {
    public static table_name:string = "JsonArray" ;

    public JsonArray_id:number;
    public JsonArray_content:string;
}