///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class JsonArray_stub extends stub.DataObject {

    /* key */
    protected static __JsonArray_id():string {
      return "JsonArray_id";
    }

    protected static __JsonArray_content():string {
      return "JsonArray_content";
    }

    /* implement DataObject */
    tableName():string {
      return "JsonArray";
    }
    
    uniqueKeyList():string[] {
      var list:string[] = [];
      list.push("JsonArray_id");
      return list;
    }
    
    allKeyList():string[] {
      var list:string[] = [];
      list.push("JsonArray_id");
      list.push("JsonArray_content");
      return list;
    }
    
    parseObject(rawObject:any):JsonArray_stub {
      var instance = new JsonArray_stub();
      if(rawObject.hasOwnProperty('JsonArray_id'))
        instance.JsonArray_id = rawObject.JsonArray_id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('JsonArray_content'))
        instance.JsonArray_content = rawObject.JsonArray_content;
      else
        throw new stub.DataObjectParseError(this);
      return instance;
    }
    
    toObject(instance:JsonArray_stub=this):any {
      var rawObject = {};
      rawObject[JsonArray_stub.__JsonArray_id()] = instance.JsonArray_id;
      rawObject[JsonArray_stub.__JsonArray_content()] = instance.JsonArray_content;
      return rawObject;
    }

    /* variable */
    private JsonArray_id:number;
    private JsonArray_content:string;

    /* getter and setter */
    public get_JsonArray_id():number {
      return this.JsonArray_id * 1;
    }

    public set_JsonArray_id(newValue:number) {
      if (this.isEditSupport()) {
        this.JsonArray_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_JsonArray_content():string {
      return this.JsonArray_content ;
    }

    public set_JsonArray_content(newValue:string) {
      if (this.isEditSupport()) {
        this.JsonArray_content = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

  }
  stub.add_stub_instance(new JsonArray_stub());
}