/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Message_stub {
    public static table_name:string = "Message" ;

    public static __msg_id:string = "msg_id";
    public static __from_account_id:string = "from_account_id";
    public static __to_account_id:string = "to_account_id";
    public static __create_time:string = "create_time";
    public static __read_time:string = "read_time";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Message {
        //TODO
        var myMessage = new Message();
        myMessage.msg_id = rawObject.msg_id;
        myMessage.from_account_id = rawObject.from_account_id;
        myMessage.to_account_id = rawObject.to_account_id;
        myMessage.create_time = rawObject.create_time;
        myMessage.read_time = rawObject.read_time;
        return myMessage;
    }

    public static get_all_instance($http):Message[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Message {
    public static table_name:string = "Message" ;

    public msg_id:number;
    public from_account_id:number;
    public to_account_id:number;
    public create_time:string;
    public read_time:string;
}