///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Message_stub extends stub.DataObject {

    /* key */
    protected static __msg_id:string = "msg_id";
    protected static __from_account_id:string = "from_account_id";
    protected static __to_account_id:string = "to_account_id";
    protected static __create_time:string = "create_time";
    protected static __read_time:string = "read_time";

    /* implement DataObject */
    tableName():string {
      return "Message";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("msg_id");
      list.push("from_account_id");
      list.push("to_account_id");
      list.push("create_time");
      list.push("read_time");
      return list;
    }
    
    parseObject(rawObject:any):Message_stub {
      return null;//TODO
    }
    
    toObject(instant:Message_stub):any {
      return null;//TODO
    }

    /* variable */
    private msg_id:number;
    private from_account_id:number;
    private to_account_id:number;
    private create_time:string;
    private read_time:string;

  }
}