///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Organization_stub extends stub.DataObject {

    /* key */
    protected static __organization_id():string {
      return "organization_id";
    }

    protected static __organization_type():string {
      return "organization_type";
    }

    protected static __name():string {
      return "name";
    }

    protected static __main_country():string {
      return "main_country";
    }

    /* implement DataObject */
    tableName():string {
      return "Organization";
    }
    
    uniqueKeyList():string[] {
      var list:string[] = [];
      list.push("organization_id");
      return list;
    }
    
    parseObject(rawObject:any):Organization_stub {
      return null;//TODO
    }
    
    toObject(instant:Organization_stub):any {
      return null;//TODO
    }

    /* variable */
    private organization_id:number;
    private organization_type:string;
    private name:string;
    private main_country:number;

    /* getter and setter */
    public get_organization_id():number {
      return this.organization_id;
    }

    public set_organization_id(newValue:number) {
      if (this.isEditSupport()) {
        this.organization_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_organization_type():string {
      return this.organization_type;
    }

    public set_organization_type(newValue:string) {
      if (this.isEditSupport()) {
        this.organization_type = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_name():string {
      return this.name;
    }

    public set_name(newValue:string) {
      if (this.isEditSupport()) {
        this.name = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_main_country():number {
      return this.main_country;
    }

    public set_main_country(newValue:number) {
      if (this.isEditSupport()) {
        this.main_country = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

  }
}