///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Organization_stub extends stub.DataObject {

    /* key */
    protected static __organization_id:string = "organization_id";
    protected static __organization_type:string = "organization_type";
    protected static __name:string = "name";
    protected static __main_country:string = "main_country";

    /* implement DataObject */
    tableName():string {
      return "Organization";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("organization_id");
      list.push("organization_type");
      list.push("name");
      list.push("main_country");
      return list;
    }
    
    parseObject(rawObject:any):Organization_stub {
      return null;//TODO
    }
    
    toObject(instant:Organization_stub):any {
      return null;//TODO
    }

    /* variable */
    private organization_id:number;
    private organization_type:string;
    private name:string;
    private main_country:number;

  }
}