/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */

///<reference path="../models.ts"/>

function load_all_typescript_class(){
    loadModel('ts/stub/Account.js');
    loadModel('ts/stub/Announcement.js');
    loadModel('ts/stub/Attraction.js');
    loadModel('ts/stub/City.js');
    loadModel('ts/stub/Country.js');
    loadModel('ts/stub/Event.js');
    loadModel('ts/stub/Event_Attendee.js');
    loadModel('ts/stub/Event_Organization.js');
    loadModel('ts/stub/Exhibition.js');
    loadModel('ts/stub/Floor.js');
    loadModel('ts/stub/Friendship.js');
    loadModel('ts/stub/Friendship_Tag.js');
    loadModel('ts/stub/Image.js');
    loadModel('ts/stub/JsonArray.js');
    loadModel('ts/stub/Message.js');
    loadModel('ts/stub/Organization.js');
    loadModel('ts/stub/Session.js');
    loadModel('ts/stub/Tag.js');
    loadModel('ts/stub/Title.js');
    loadModel('ts/stub/User.js');
    loadModel('ts/stub/Venus.js');
}