/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */

///<reference path="../models.ts"/>

function load_all_typescript_class(){
    loadModel('ts/stub/Account_stub.js');
    loadModel('ts/stub/Announcement_stub.js');
    loadModel('ts/stub/Attraction_stub.js');
    loadModel('ts/stub/City_stub.js');
    loadModel('ts/stub/Country_stub.js');
    loadModel('ts/stub/DiscussBoard_stub.js');
    loadModel('ts/stub/Event_stub.js');
    loadModel('ts/stub/Event_Attendee_stub.js');
    loadModel('ts/stub/Event_Organization_stub.js');
    loadModel('ts/stub/Exhibition_stub.js');
    loadModel('ts/stub/Floor_stub.js');
    loadModel('ts/stub/Friendship_stub.js');
    loadModel('ts/stub/Friendship_Tag_stub.js');
    loadModel('ts/stub/Image_stub.js');
    loadModel('ts/stub/JsonArray_stub.js');
    loadModel('ts/stub/Message_stub.js');
    loadModel('ts/stub/Organization_stub.js');
    loadModel('ts/stub/Post_stub.js');
    loadModel('ts/stub/Reply_stub.js');
    loadModel('ts/stub/Session_stub.js');
    loadModel('ts/stub/Tag_stub.js');
    loadModel('ts/stub/Title_stub.js');
    loadModel('ts/stub/User_stub.js');
    loadModel('ts/stub/Venus_stub.js');
}