///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Post_stub extends stub.DataObject {

    /* key */
    protected static __post_Id:string = "post_Id";
    protected static __subject:string = "subject";
    protected static __description:string = "description";
    protected static __discussboard_id:string = "discussboard_id";

    /* implement DataObject */
    tableName():string {
      return "Post";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("post_Id");
      list.push("subject");
      list.push("description");
      list.push("discussboard_id");
      return list;
    }
    
    parseObject(rawObject:any):Post_stub {
      return null;//TODO
    }
    
    toObject(instant:Post_stub):any {
      return null;//TODO
    }

    /* variable */
    private post_Id:number;
    private subject:string;
    private description:string;
    private discussboard_id:number;

  }
}