///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Post_stub extends stub.DataObject {

    /* key */
    protected static __post_Id():string {
      return "post_Id";
    }

    protected static __subject():string {
      return "subject";
    }

    protected static __description():string {
      return "description";
    }

    protected static __discussboard_id():string {
      return "discussboard_id";
    }

    protected static __creator_account_id():string {
      return "creator_account_id";
    }

    protected static __editor_account_id():string {
      return "editor_account_id";
    }

    protected static __create_time():string {
      return "create_time";
    }

    protected static __edit_time():string {
      return "edit_time";
    }

    protected static __deleted():string {
      return "deleted";
    }

    /* implement DataObject */
    tableName():string {
      return "Post";
    }
    
    uniqueKeyList():string[] {
      var list:string[] = [];
      list.push("post_Id");
      return list;
    }
    
    parseObject(rawObject:any):Post_stub {
      var instance = new Post_stub();
      if(rawObject.hasOwnProperty('post_Id'))
        instance.post_Id = rawObject.post_Id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('subject'))
        instance.subject = rawObject.subject;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('description'))
        instance.description = rawObject.description;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('discussboard_id'))
        instance.discussboard_id = rawObject.discussboard_id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('creator_account_id'))
        instance.creator_account_id = rawObject.creator_account_id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('editor_account_id'))
        instance.editor_account_id = rawObject.editor_account_id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('create_time'))
        instance.create_time = rawObject.create_time;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('edit_time'))
        instance.edit_time = rawObject.edit_time;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('deleted'))
        instance.deleted = rawObject.deleted;
      else
        throw new stub.DataObjectParseError(this);
      return instance;
    }
    
    toObject(instance:Post_stub=this):any {
      var rawObject = {};
      rawObject[Post_stub.__post_Id()] = instance.post_Id;
      rawObject[Post_stub.__subject()] = instance.subject;
      rawObject[Post_stub.__description()] = instance.description;
      rawObject[Post_stub.__discussboard_id()] = instance.discussboard_id;
      rawObject[Post_stub.__creator_account_id()] = instance.creator_account_id;
      rawObject[Post_stub.__editor_account_id()] = instance.editor_account_id;
      rawObject[Post_stub.__create_time()] = instance.create_time;
      rawObject[Post_stub.__edit_time()] = instance.edit_time;
      rawObject[Post_stub.__deleted()] = instance.deleted;
      return rawObject;
    }

    /* variable */
    private post_Id:number;
    private subject:string;
    private description:string;
    private discussboard_id:number;
    private creator_account_id:number;
    private editor_account_id:number;
    private create_time:string;
    private edit_time:string;
    private deleted:any;

    /* getter and setter */
    public get_post_Id():number {
      return this.post_Id;
    }

    public set_post_Id(newValue:number) {
      if (this.isEditSupport()) {
        this.post_Id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_subject():string {
      return this.subject;
    }

    public set_subject(newValue:string) {
      if (this.isEditSupport()) {
        this.subject = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_description():string {
      return this.description;
    }

    public set_description(newValue:string) {
      if (this.isEditSupport()) {
        this.description = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_discussboard_id():number {
      return this.discussboard_id;
    }

    public set_discussboard_id(newValue:number) {
      if (this.isEditSupport()) {
        this.discussboard_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_creator_account_id():number {
      return this.creator_account_id;
    }

    public set_creator_account_id(newValue:number) {
      if (this.isEditSupport()) {
        this.creator_account_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_editor_account_id():number {
      return this.editor_account_id;
    }

    public set_editor_account_id(newValue:number) {
      if (this.isEditSupport()) {
        this.editor_account_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_create_time():string {
      return this.create_time;
    }

    public set_create_time(newValue:string) {
      if (this.isEditSupport()) {
        this.create_time = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_edit_time():string {
      return this.edit_time;
    }

    public set_edit_time(newValue:string) {
      if (this.isEditSupport()) {
        this.edit_time = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_deleted():any {
      return this.deleted;
    }

    public set_deleted(newValue:any) {
      if (this.isEditSupport()) {
        this.deleted = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

  }
  stub.add_stub_instance(new Post_stub());
}