/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Post_stub {
    public static table_name:string = "Post" ;

    public static __post_Id:string = "post_Id";
    public static __subject:string = "subject";
    public static __description:string = "description";
    public static __discussboard_id:string = "discussboard_id";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Post {
        //TODO
        var myPost = new Post();
        myPost.post_Id = rawObject.post_Id;
        myPost.subject = rawObject.subject;
        myPost.description = rawObject.description;
        myPost.discussboard_id = rawObject.discussboard_id;
        return myPost;
    }

    public static get_all_instance($http):Post[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Post {
    public static table_name:string = "Post" ;

    public post_Id:number;
    public subject:string;
    public description:string;
    public discussboard_id:number;
}