/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Reply_stub {
    public static table_name:string = "Reply" ;

    public static __reply_id:string = "reply_id";
    public static __post_Id:string = "post_Id";
    public static __message:string = "message";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Reply {
        //TODO
        var myReply = new Reply();
        myReply.reply_id = rawObject.reply_id;
        myReply.post_Id = rawObject.post_Id;
        myReply.message = rawObject.message;
        return myReply;
    }

    public static get_all_instance($http):Reply[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Reply {
    public static table_name:string = "Reply" ;

    public reply_id:number;
    public post_Id:number;
    public message:string;
}