///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Reply_stub extends stub.DataObject {

    /* key */
    protected static __reply_id:string = "reply_id";
    protected static __post_Id:string = "post_Id";
    protected static __message:string = "message";
    protected static __account_id:string = "account_id";

    /* implement DataObject */
    tableName():string {
      return "Reply";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("reply_id");
      list.push("post_Id");
      list.push("message");
      list.push("account_id");
      return list;
    }
    
    parseObject(rawObject:any):Reply_stub {
      return null;//TODO
    }
    
    toObject(instant:Reply_stub):any {
      return null;//TODO
    }

    /* variable */
    private reply_id:number;
    private post_Id:number;
    private message:string;
    private account_id:number;

  }
}