///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Reward_stub extends stub.DataObject {

    /* key */
    protected static __reward_id():string {
      return "reward_id";
    }

    protected static __reward_type():string {
      return "reward_type";
    }

    protected static __amount():string {
      return "amount";
    }

    protected static __collection_venue():string {
      return "collection_venue";
    }

    protected static __status():string {
      return "status";
    }

    protected static __receiver_id():string {
      return "receiver_id";
    }

    protected static __sender_id():string {
      return "sender_id";
    }

    /* implement DataObject */
    tableName():string {
      return "Reward";
    }
    
    uniqueKeyList():string[] {
      var list:string[] = [];
      list.push("reward_id");
      return list;
    }
    
    parseObject(rawObject:any):Reward_stub {
      var instance = new Reward_stub();
      if(rawObject.hasOwnProperty('reward_id'))
        instance.reward_id = rawObject.reward_id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('reward_type'))
        instance.reward_type = rawObject.reward_type;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('amount'))
        instance.amount = rawObject.amount;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('collection_venue'))
        instance.collection_venue = rawObject.collection_venue;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('status'))
        instance.status = rawObject.status;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('receiver_id'))
        instance.receiver_id = rawObject.receiver_id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('sender_id'))
        instance.sender_id = rawObject.sender_id;
      else
        throw new stub.DataObjectParseError(this);
      return instance;
    }
    
    toObject(instance:Reward_stub=this):any {
      var rawObject = {};
      rawObject[Reward_stub.__reward_id()] = instance.reward_id;
      rawObject[Reward_stub.__reward_type()] = instance.reward_type;
      rawObject[Reward_stub.__amount()] = instance.amount;
      rawObject[Reward_stub.__collection_venue()] = instance.collection_venue;
      rawObject[Reward_stub.__status()] = instance.status;
      rawObject[Reward_stub.__receiver_id()] = instance.receiver_id;
      rawObject[Reward_stub.__sender_id()] = instance.sender_id;
      return rawObject;
    }

    /* variable */
    private reward_id:number;
    private reward_type:string;
    private amount:any;
    private collection_venue:number;
    private status:string;
    private receiver_id:number;
    private sender_id:number;

    /* getter and setter */
    public get_reward_id():number {
      return this.reward_id;
    }

    public set_reward_id(newValue:number) {
      if (this.isEditSupport()) {
        this.reward_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_reward_type():string {
      return this.reward_type;
    }

    public set_reward_type(newValue:string) {
      if (this.isEditSupport()) {
        this.reward_type = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_amount():any {
      return this.amount;
    }

    public set_amount(newValue:any) {
      if (this.isEditSupport()) {
        this.amount = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_collection_venue():number {
      return this.collection_venue;
    }

    public set_collection_venue(newValue:number) {
      if (this.isEditSupport()) {
        this.collection_venue = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_status():string {
      return this.status;
    }

    public set_status(newValue:string) {
      if (this.isEditSupport()) {
        this.status = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_receiver_id():number {
      return this.receiver_id;
    }

    public set_receiver_id(newValue:number) {
      if (this.isEditSupport()) {
        this.receiver_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_sender_id():number {
      return this.sender_id;
    }

    public set_sender_id(newValue:number) {
      if (this.isEditSupport()) {
        this.sender_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

  }
}