/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Session_stub {
    public static table_name:string = "Session" ;

    public static __event_id:string = "event_id";
    public static __quota:string = "quota";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Session {
        //TODO
        var mySession = new Session();
        mySession.event_id = rawObject.event_id;
        mySession.quota = rawObject.quota;
        return mySession;
    }

    public static get_all_instance($http):Session[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Session {
    public static table_name:string = "Session" ;

    public event_id:number;
    public quota:number;
}