/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Tag_stub {
    public static table_name:string = "Tag" ;

    public static __tag_id:string = "tag_id";
    public static __tag_content:string = "tag_content";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Tag {
        //TODO
        var myTag = new Tag();
        myTag.tag_id = rawObject.tag_id;
        myTag.tag_content = rawObject.tag_content;
        return myTag;
    }

    public static get_all_instance($http):Tag[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Tag {
    public static table_name:string = "Tag" ;

    public tag_id:number;
    public tag_content:string;
}