///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Tag_stub extends stub.DataObject {

    /* key */
    protected static __tag_id:string = "tag_id";
    protected static __tag_content:string = "tag_content";

    /* implement DataObject */
    tableName():string {
      return "Tag";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("tag_id");
      list.push("tag_content");
      return list;
    }
    
    parseObject(rawObject:any):Tag_stub {
      return null;//TODO
    }
    
    toObject(instant:Tag_stub):any {
      return null;//TODO
    }

    /* variable */
    private tag_id:number;
    private tag_content:string;

  }
}