/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Title_stub {
    public static table_name:string = "Title" ;

    public static __title_id:string = "title_id";
    public static __title_text:string = "title_text";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Title {
        //TODO
        var myTitle = new Title();
        myTitle.title_id = rawObject.title_id;
        myTitle.title_text = rawObject.title_text;
        return myTitle;
    }

    public static get_all_instance($http):Title[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Title {
    public static table_name:string = "Title" ;

    public title_id:number;
    public title_text:string;
}