///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Title_stub extends stub.DataObject {

    /* key */
    protected static __title_id:string = "title_id";
    protected static __title_text:string = "title_text";

    /* implement DataObject */
    tableName():string {
      return "Title";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("title_id");
      list.push("title_text");
      return list;
    }
    
    parseObject(rawObject:any):Title_stub {
      return null;//TODO
    }
    
    toObject(instant:Title_stub):any {
      return null;//TODO
    }

    /* variable */
    private title_id:number;
    private title_text:string;

  }
}