/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class User_stub {
    public static table_name:string = "User" ;

    public static __account_id:string = "account_id";
    public static __sex:string = "sex";
    public static __first_name:string = "first_name";
    public static __last_name:string = "last_name";
    public static __organization_id:string = "organization_id";
    public static __title_id:string = "title_id";
    public static __city_id:string = "city_id";
    public static __last_announcement_datetime:string = "last_announcement_datetime";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):User {
        //TODO
        var myUser = new User();
        myUser.account_id = rawObject.account_id;
        myUser.sex = rawObject.sex;
        myUser.first_name = rawObject.first_name;
        myUser.last_name = rawObject.last_name;
        myUser.organization_id = rawObject.organization_id;
        myUser.title_id = rawObject.title_id;
        myUser.city_id = rawObject.city_id;
        myUser.last_announcement_datetime = rawObject.last_announcement_datetime;
        return myUser;
    }

    public static get_all_instance($http):User[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class User {
    public static table_name:string = "User" ;

    public account_id:number;
    public sex:string;
    public first_name:string;
    public last_name:string;
    public organization_id:number;
    public title_id:number;
    public city_id:number;
    public last_announcement_datetime:string;
}