///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class User_stub extends stub.DataObject {

    /* key */
    protected static __account_id:string = "account_id";
    protected static __sex:string = "sex";
    protected static __first_name:string = "first_name";
    protected static __last_name:string = "last_name";
    protected static __organization_id:string = "organization_id";
    protected static __title_id:string = "title_id";
    protected static __city_id:string = "city_id";
    protected static __last_announcement_datetime:string = "last_announcement_datetime";

    /* implement DataObject */
    tableName():string {
      return "User";
    }
    
    uniqueKeyList():string[] {
      var list : string[] = [];
      list.push("account_id");
      list.push("sex");
      list.push("first_name");
      list.push("last_name");
      list.push("organization_id");
      list.push("title_id");
      list.push("city_id");
      list.push("last_announcement_datetime");
      return list;
    }
    
    parseObject(rawObject:any):User_stub {
      return null;//TODO
    }
    
    toObject(instant:User_stub):any {
      return null;//TODO
    }

    /* variable */
    private account_id:number;
    private sex:string;
    private first_name:string;
    private last_name:string;
    private organization_id:number;
    private title_id:number;
    private city_id:number;
    private last_announcement_datetime:string;

  }
}