/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
class Venus_stub {
    public static table_name:string = "Venus" ;

    public static __venue_id:string = "venue_id";
    public static __floor_id:string = "floor_id";

    private static getObject($http) {
        get_all_row($http,this.table_name)
    }

    private static parseObject(rawObject:any):Venus {
        //TODO
        var myVenus = new Venus();
        myVenus.venue_id = rawObject.venue_id;
        myVenus.floor_id = rawObject.floor_id;
        return myVenus;
    }

    public static get_all_instance($http):Venus[] {
        var all_row = get_all_row($http,this.table_name);
        return all_row.map(row => this.parseObject(row));
    }

}
class Venus {
    public static table_name:string = "Venus" ;

    public venue_id:number;
    public floor_id:number;
}