///<reference path="DataObject.ts"/>
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
declare function get_all_row($http: any, table_name: string) : any[];
module stub {
  export class Venue_stub extends stub.DataObject {

    /* key */
    protected static __venue_id():string {
      return "venue_id";
    }

    protected static __floor_id():string {
      return "floor_id";
    }

    protected static __venue_name():string {
      return "venue_name";
    }

    /* implement DataObject */
    tableName():string {
      return "Venue";
    }
    
    uniqueKeyList():string[] {
      var list:string[] = [];
      list.push("venue_id");
      return list;
    }
    
    allKeyList():string[] {
      var list:string[] = [];
      list.push("venue_id");
      list.push("floor_id");
      list.push("venue_name");
      return list;
    }
    
    parseObject(rawObject:any):Venue_stub {
      var instance = new Venue_stub();
      if(rawObject.hasOwnProperty('venue_id'))
        instance.venue_id = rawObject.venue_id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('floor_id'))
        instance.floor_id = rawObject.floor_id;
      else
        throw new stub.DataObjectParseError(this);
      if(rawObject.hasOwnProperty('venue_name'))
        instance.venue_name = rawObject.venue_name;
      else
        throw new stub.DataObjectParseError(this);
      return instance;
    }
    
    toObject(instance:Venue_stub=this):any {
      var rawObject = {};
      rawObject[Venue_stub.__venue_id()] = instance.venue_id;
      rawObject[Venue_stub.__floor_id()] = instance.floor_id;
      rawObject[Venue_stub.__venue_name()] = instance.venue_name;
      return rawObject;
    }

    /* variable */
    private venue_id:number;
    private floor_id:number;
    private venue_name:string;

    /* getter and setter */
    public get_venue_id():number {
      return this.venue_id * 1;
    }

    public set_venue_id(newValue:number) {
      if (this.isEditSupport()) {
        this.venue_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_floor_id():number {
      return this.floor_id * 1;
    }

    public set_floor_id(newValue:number) {
      if (this.isEditSupport()) {
        this.floor_id = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

    public get_venue_name():string {
      return this.venue_name ;
    }

    public set_venue_name(newValue:string) {
      if (this.isEditSupport()) {
        this.venue_name = newValue;
      } else {
        throw new DataObjectEditError(this);
      }
    }

  }
  stub.add_stub_instance(new Venue_stub());
}