<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Announcement_Fields {
    const _ = "Announcement" ;
    const _insert_sql = "database/prepared_statement/Announcement_insert.sql" ;
    const __announcement_id = "announcement_id" ;
    const __subject = "subject" ;
    const __description = "description" ;
    const __create_time = "create_time" ;
    const __creator_account_id = "creator_account_id" ;
}