<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Attraction_Fields {
    const _ = "Attraction" ;
    const _insert_sql = "database/prepared_statement/Attraction_insert.sql" ;
    const __event_id = "event_id" ;
}