<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class City_Fields {
    const _ = "City" ;
    const _insert_sql = "database/prepared_statement/City_insert.sql" ;
    const __city_id = "city_id" ;
    const __country_id = "country_id" ;
    const __city_name = "city_name" ;
}