<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Country_Fields {
    const _ = "Country" ;
    const _insert_sql = "database/prepared_statement/Country_insert.sql" ;
    const __country_id = "country_id" ;
    const __country_name = "country_name" ;
}