<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class DiscussBoard_Fields {
    const _ = "DiscussBoard" ;
    const _insert_sql = "database/prepared_statement/DiscussBoard_insert.sql" ;
    const __discussboard_id = "discussboard_id" ;
    const __subject = "subject" ;
    const __description = "description" ;
}