<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Event_Fields {
    const _ = "Event" ;
    const _insert_sql = "database/prepared_statement/Event_insert.sql" ;
    const __event_id = "event_id" ;
    const __create_time = "create_time" ;
    const __edit_time = "edit_time" ;
    const __event_type = "event_type" ;
    const __venue_id = "venue_id" ;
    const __event_time = "event_time" ;
    const __creator_account_id = "creator_account_id" ;
    const __editor_account_id = "editor_account_id" ;
    const __subject = "subject" ;
    const __description = "description" ;
    const __quota = "quota" ;
    const __venue = "venue" ;
}