<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Exhibition_Fields {
    const _ = "Exhibition" ;
    const _insert_sql = "database/prepared_statement/Exhibition_insert.sql" ;
    const __event_id = "event_id" ;
}