<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Floor_Fields {
    const _ = "Floor" ;
    const _insert_sql = "database/prepared_statement/Floor_insert.sql" ;
    const __floor_id = "floor_id" ;
    const __floor_name = "floor_name" ;
}