<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Follow_Fields {
    const _ = "Follow" ;
    const _insert_sql = "database/prepared_statement/Follow_insert.sql" ;
    const __follow_id = "follow_id" ;
    const __follower_account_id = "follower_account_id" ;
    const __followed_account_id = "followed_account_id" ;
    const __remark = "remark" ;
    const __deleted = "deleted" ;
    const __create_time = "create_time" ;
    const __edit_time = "edit_time" ;
}