<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Friendship_Tag_Fields {
    const _ = "Friendship_Tag" ;
    const _insert_sql = "database/prepared_statement/Friendship_Tag_insert.sql" ;
    const __friendship_id = "friendship_id" ;
    const __tag_id = "tag_id" ;
}