<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Image_Fields {
    const _ = "Image" ;
    const _insert_sql = "database/prepared_statement/Image_insert.sql" ;
    const __image_id = "image_id" ;
    const __url = "url" ;
}