<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Message_Fields {
    const _ = "Message" ;
    const _insert_sql = "database/prepared_statement/Message_insert.sql" ;
    const __msg_id = "msg_id" ;
    const __from_account_id = "from_account_id" ;
    const __to_account_id = "to_account_id" ;
    const __create_time = "create_time" ;
    const __read_time = "read_time" ;
}