<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
include_once 'Account_Field.php';
include_once 'Announcement_Field.php';
include_once 'Attraction_Field.php';
include_once 'City_Field.php';
include_once 'Country_Field.php';
include_once 'DiscussBoard_Field.php';
include_once 'Event_Field.php';
include_once 'Event_Attendee_Field.php';
include_once 'Event_Organization_Field.php';
include_once 'Exhibition_Field.php';
include_once 'Floor_Field.php';
include_once 'Follow_Field.php';
include_once 'Friendship_Tag_Field.php';
include_once 'Image_Field.php';
include_once 'JsonArray_Field.php';
include_once 'Message_Field.php';
include_once 'Organization_Field.php';
include_once 'Post_Field.php';
include_once 'Reply_Field.php';
include_once 'Reward_Field.php';
include_once 'Session_Field.php';
include_once 'SessionReply_Field.php';
include_once 'Tag_Field.php';
include_once 'Title_Field.php';
include_once 'User_Field.php';
include_once 'Venue_Field.php';