<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Post_Fields {
    const _ = "Post" ;
    const _insert_sql = "database/prepared_statement/Post_insert.sql" ;
    const __post_Id = "post_Id" ;
    const __subject = "subject" ;
    const __description = "description" ;
    const __discussboard_id = "discussboard_id" ;
}