<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Reply_Fields {
    const _ = "Reply" ;
    const _insert_sql = "database/prepared_statement/Reply_insert.sql" ;
    const __reply_id = "reply_id" ;
    const __post_Id = "post_Id" ;
    const __message = "message" ;
    const __account_id = "account_id" ;
}