<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Reply_Fields {
    const _ = "Reply" ;
    const _insert_sql = "database/prepared_statement/Reply_insert.sql" ;
    const __reply_id = "reply_id" ;
    const __post_Id = "post_Id" ;
    const __message = "message" ;
    const __creator_account_id = "creator_account_id" ;
    const __editor_account_id = "editor_account_id" ;
    const __create_time = "create_time" ;
    const __edit_time = "edit_time" ;
    const __deleted = "deleted" ;
}