<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Reward_Fields {
    const _ = "Reward" ;
    const _insert_sql = "database/prepared_statement/Reward_insert.sql" ;
    const __reward_id = "reward_id" ;
    const __reward_type = "reward_type" ;
    const __amount = "amount" ;
    const __collection_venue = "collection_venue" ;
    const __status = "status" ;
    const __receiver_id = "receiver_id" ;
    const __sender_id = "sender_id" ;
}