<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Session_Fields {
    const _ = "Session" ;
    const _insert_sql = "database/prepared_statement/Session_insert.sql" ;
    const __event_id = "event_id" ;
}