<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Title_Fields {
    const _ = "Title" ;
    const _insert_sql = "database/prepared_statement/Title_insert.sql" ;
    const __title_id = "title_id" ;
    const __title_text = "title_text" ;
}