<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class User_Fields {
    const _ = "User" ;
    const _insert_sql = "database/prepared_statement/User_insert.sql" ;
    const __account_id = "account_id" ;
    const __sex = "sex" ;
    const __first_name = "first_name" ;
    const __last_name = "last_name" ;
    const __organization_id = "organization_id" ;
    const __title_id = "title_id" ;
    const __city_id = "city_id" ;
    const __last_announcement_datetime = "last_announcement_datetime" ;
    const __organization = "organization" ;
    const __city = "city" ;
    const __country = "country" ;
    const __title = "title" ;
}