<?php
/** @remark this is auto-generated file, do not edit
 * generated by php script
 * */
class Venue_Fields {
    const _ = "Venue" ;
    const _insert_sql = "database/prepared_statement/Venue_insert.sql" ;
    const __venue_id = "venue_id" ;
    const __floor_id = "floor_id" ;
    const __venue_name = "venue_name" ;
}