<?php
/** @remark this is auto-generated file, do not edit
 * generated by bash script
 * */

class APIFieldEnum
{
    const _ = "APIField";
    const _action = "action";
    const _result_code = "result_code";
    const _data = "data";
    const _reason = "reason";
    const _emailOrPhoneNum = "emailOrPhoneNum";
    const _password = "password";
    const _session_id = "session_id";
    const _element_array = "element_array";
    const _profile = "profile";
    const _table_name_array = "table_name_array";
    const _table_name = "table_name";
    const _latest_id = "latest_id";
    const _id_array = "id_array";
    const _id = "id";
    const _field_array = "field_array";
    const _message = "message";
    const _followed = "followed";
    const _following = "following";
    const _joined = "joined";
    const _join_time = "join_time";
    const _user_count = "user_count";
}
