<?php
/** @remark this is auto-generated file, do not edit
 * generated by bash script
 * */

class APIFieldEnum
{
    const _ = "APIField";
    const _action = "action";
    const _result_code = "result_code";
    const _reason = "reason";
    const _session_id = "session_id";
    const _element_array = "element_array";
    const _profile = "profile";
    const _follower_user_id = "follower_user_id";
    const _followed_user_id = "followed_user_id";
    const _table_name_array = "table_name_array";
    const _table_name = "table_name";
    const _latest_id = "latest_id";
    const _id_array = "id_array";
    const _field_array = "field_array";
}
